"""empty message

Revision ID: 2dc35b449e8a
Revises: 4416a8676605
Create Date: 2024-01-23 22:36:09.773228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc35b449e8a'
down_revision = '4416a8676605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.alter_column('government',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('continent_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.alter_column('continent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('government',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
