"""empty message

Revision ID: 4b0f722c0ae6
Revises: 6bfa9bf6841a
Create Date: 2024-01-16 16:04:36.425474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b0f722c0ae6'
down_revision = '6bfa9bf6841a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('government', sa.String(length=50), nullable=False),
    sa.Column('continent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['continent_id'], ['continent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('is_capital', sa.Boolean(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('country_capital_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_capital_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_capital_id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('continent', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('continent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('city')
    op.drop_table('country')
    # ### end Alembic commands ###
